runtime: python38

instance_class: F1

env_variables:
  MYSQL_DB: 'xstream'
  MYSQL_HOST: '34.67.16.67'
  MYSQL_CONN_NAME: 'xstream-999999:us-central1:xstreamv2'

handlers:
- url: /images
  static_dir: static/images

- url: /scripts
  static_dir: static/scripts

- url: /styles
  static_dir: static/styles